export const TRACKS_GET_FETCHING = '@@tracks/TRACKS_GET_FETCHING'
export const TRACKS_GET_SUCCESS = '@@tracks/TRACKS_GET_SUCCESS'
export const TRACKS_GET_ERROR = '@@tracks/TRACKS_GET_ERROR'

export const TRACK_TOGGLE_PRIORITY = '@@tracks/TRACK_TOGGLE_PRIORITY'
export const TRACK_TOGGLE_UPVOTE = '@@tracks/TRACK_TOGGLE_UPVOTE'
